# Generated by Django 4.2.5 on 2023-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_category_movie_category_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
